// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using EntityFrameworkEnumSimple.Classes;

namespace EntityFrameworkEnumSimple.Models
{
    public partial class Book
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public BookCategory BookCategory { get; set; }
    }

    public class BookVariant
    {
        [Key]
        public BookCategory BookCategoryId { get; set; }
        public string Name { get; set; }

        public List<Book> Books { get; set; }
    }
}