// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FilteredInclude.Data;
using FilteredInclude.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace FilteredInclude.Data.Configurations
{
    public partial class ProductsConfiguration : IEntityTypeConfiguration<Products>
    {
        public void Configure(EntityTypeBuilder<Products> entity)
        {
            entity.Property(e => e.ProductID).HasComment("This is the primary key for a single product");

            entity.Property(e => e.ProductName).HasComment("This is the product name of the product");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Products> entity);
    }
}
