
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataGridViewEntityChecked.Models
{
    public partial class Categories
    {
        [NotMapped]
        [DefaultValue(false)]
        public bool Checked { get; set; }

        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}