
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HasConversion.Models
{
    public partial class Account
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public bool? Active { get; set; }
        public DateTime? CreatedDate { get; set; }
        /// <summary>
        /// This property has a conversion in the DbContext
        /// </summary>
        public string[] Roles { get; set; }


    }
}