/*
	IMPORTANT

	For OED developers create the database in SSMS, select lines 106 to end of file and run the script
	For other developer, change the database path, change the new user starting on line 84 to you and run the entire script
*/
USE [master]
GO
/****** Object:  Database [BookCatalog]    Script Date: 6/8/2022 10:33:48 AM ******/
CREATE DATABASE [BookCatalog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookCatalog', FILENAME = N'C:\Users\paynek\BookCatalog.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BookCatalog_log', FILENAME = N'C:\Users\paynek\BookCatalog_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [BookCatalog] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookCatalog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BookCatalog] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BookCatalog] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BookCatalog] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BookCatalog] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BookCatalog] SET ARITHABORT OFF 
GO
ALTER DATABASE [BookCatalog] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BookCatalog] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BookCatalog] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BookCatalog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BookCatalog] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BookCatalog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BookCatalog] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BookCatalog] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BookCatalog] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BookCatalog] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BookCatalog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BookCatalog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BookCatalog] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BookCatalog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BookCatalog] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BookCatalog] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BookCatalog] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BookCatalog] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BookCatalog] SET  MULTI_USER 
GO
ALTER DATABASE [BookCatalog] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BookCatalog] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BookCatalog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BookCatalog] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [BookCatalog] SET DELAYED_DURABILITY = DISABLED 
GO
USE [BookCatalog]
GO
/****** Object:  User [OED\paynek]    Script Date: 6/8/2022 10:33:49 AM ******/
CREATE USER [OED\paynek] FOR LOGIN [OED\paynek] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [OED\paynek]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [OED\paynek]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [OED\paynek]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [OED\paynek]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [OED\paynek]
GO
ALTER ROLE [db_datareader] ADD MEMBER [OED\paynek]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [OED\paynek]
GO
ALTER ROLE [db_denydatareader] ADD MEMBER [OED\paynek]
GO
ALTER ROLE [db_denydatawriter] ADD MEMBER [OED\paynek]
GO
/****** Object:  Table [dbo].[Book]    Script Date: 6/8/2022 10:33:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NULL,
	[Price] [decimal](18, 0) NULL,
 CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Book] ON 
GO
INSERT [dbo].[Book] ([Id], [Title], [Price]) VALUES (1, N'Learn EF Core', CAST(19 AS Decimal(18, 0)))
GO
INSERT [dbo].[Book] ([Id], [Title], [Price]) VALUES (2, N'C# Basics', CAST(18 AS Decimal(18, 0)))
GO
INSERT [dbo].[Book] ([Id], [Title], [Price]) VALUES (3, N'ASP.NET Core advance', CAST(30 AS Decimal(18, 0)))
GO
INSERT [dbo].[Book] ([Id], [Title], [Price]) VALUES (4, N'VB.NET To C#', CAST(9 AS Decimal(18, 0)))
GO
INSERT [dbo].[Book] ([Id], [Title], [Price]) VALUES (5, N'Basic Azure', CAST(59 AS Decimal(18, 0)))
GO
SET IDENTITY_INSERT [dbo].[Book] OFF
GO
USE [master]
GO
ALTER DATABASE [BookCatalog] SET  READ_WRITE 
GO
